"use client";
import { useActionState, useMemo } from "react";
import { createTicketAction, type ActionState } from "@/app/(portal)/actions";
import { AlertCircle, ArrowRight } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "./ui/alert";
import { Button } from "./ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "./ui/card";
import { Input } from "./ui/input";
import { Label } from "./ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "./ui/select";
import { Textarea } from "./ui/textarea";

const initial: ActionState = {};
const categories = ["Computer / Laptop", "Password / Login", "Email", "Microsoft Office", "Printer / Scanner", "Internet / Wi-Fi", "Phone", "Software", "Access / Permissions", "Equipment", "Website", "New Employee Setup", "Other"];

export function TicketForm({ defaultLocation }: { defaultLocation: string }) {
  const [state, action, pending] = useActionState(createTicketAction, initial);
  const operationUid = useMemo(() => crypto.randomUUID(), []);
  return <form action={action} className="space-y-6"><input type="hidden" name="operationUid" value={operationUid}/>{state.error&&<Alert variant="destructive"><AlertCircle/><AlertTitle>We could not submit this request</AlertTitle><AlertDescription>{state.error}</AlertDescription></Alert>}<Card><CardHeader><CardTitle>What do you need help with?</CardTitle></CardHeader><CardContent className="grid gap-5"><Field id="category" label="Category" error={state.fields?.category}><Select name="category" required><SelectTrigger id="category" className="w-full"><SelectValue placeholder="Choose the closest match"/></SelectTrigger><SelectContent>{categories.map((category)=><SelectItem key={category} value={category}>{category}</SelectItem>)}</SelectContent></Select></Field><Field id="subject" label="What’s happening?" hint="A short summary helps IT scan the queue." error={state.fields?.subject}><Input id="subject" name="subject" maxLength={140} placeholder="Example: Laptop cannot connect to Wi-Fi" required/></Field><Field id="description" label="Tell us what happened and what you were trying to do" error={state.fields?.description}><Textarea id="description" name="description" rows={7} maxLength={8000} placeholder="Include any error message, when it started, and what you already tried." required/></Field></CardContent></Card><Card><CardHeader><CardTitle>Help us understand the impact</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><Field id="impact" label="Who is affected?"><Select name="impact" defaultValue="ONE"><SelectTrigger id="impact" className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="ONE">Only me</SelectItem><SelectItem value="SEVERAL">Several people</SelectItem><SelectItem value="MANY">Most or all staff</SelectItem></SelectContent></Select></Field><Field id="locationUid" label="Where do you need help?"><Input id="locationUid" name="locationUid" defaultValue={defaultLocation}/></Field><label className="flex min-h-14 items-center gap-3 rounded-xl border p-4 text-sm"><input className="size-4 accent-primary" type="checkbox" name="workBlocked"/><span><strong className="block">I cannot continue working</strong><span className="text-muted-foreground">This issue is blocking my main task.</span></span></label><label className="flex min-h-14 items-center gap-3 rounded-xl border p-4 text-sm"><input className="size-4 accent-primary" type="checkbox" name="workaroundAvailable"/><span><strong className="block">I have a temporary workaround</strong><span className="text-muted-foreground">I can keep working for now.</span></span></label><Field id="assetUid" label="Device or asset tag" hint="Optional"><Input id="assetUid" name="assetUid" placeholder="Example: LACC-LT-104"/></Field></CardContent></Card><div className="flex justify-end"><Button size="lg" type="submit" disabled={pending}>{pending?"Saving securely…":"Submit request"}<ArrowRight/></Button></div></form>;
}
function Field({id,label,hint,error,children}:{id?:string;label:string;hint?:string;error?:string;children:React.ReactNode}){return <div className="grid gap-2"><div className="flex items-end justify-between gap-3"><Label htmlFor={id}>{label}</Label>{hint&&<span className="text-xs text-muted-foreground">{hint}</span>}</div>{children}{error&&<p className="text-xs text-destructive">{error}</p>}</div>}
