import { describe, expect, it } from "vitest";
import { FixtureTicketRepository } from "@/lib/excel/fixture-repository";
import { AuthorizationError, ConflictError } from "@/lib/excel/repository";

describe("ticket repository guarantees",()=>{
  it("deduplicates a retried ticket operation",async()=>{const repo=new FixtureTicketRepository();const user=await repo.getEmployeeByEmail("employee@thelatincenter.org");expect(user).not.toBeNull();const input={operationUid:"10000000-0000-4000-8000-000000000001",subject:"Cannot open Outlook",description:"Outlook closes immediately after I open it.",category:"Email",impact:"ONE" as const,workBlocked:false,workaroundAvailable:true,locationUid:"",assetUid:""};const first=await repo.createTicket(input,user!);const second=await repo.createTicket(input,user!);expect(second.ticketUid).toBe(first.ticketUid);});
  it("rejects stale writes",async()=>{const repo=new FixtureTicketRepository();const agent=await repo.getEmployeeByEmail("agent@thelatincenter.org");const list=await repo.listTickets();await expect(repo.updateTicket(list[0].ticketUid,{operationUid:"10000000-0000-4000-8000-000000000002",expectedVersion:999,status:"RESOLVED"},agent!)).rejects.toBeInstanceOf(ConflictError);});
  it("does not return another employee ticket",async()=>{const repo=new FixtureTicketRepository();const user=await repo.getEmployeeByEmail("employee@thelatincenter.org");await expect(repo.getTicketByNumber("LACC-2026-3D91B4",user!)).rejects.toBeInstanceOf(AuthorizationError);});
  it("records legacy intake completion with the signed-in staff name",async()=>{const repo=new FixtureTicketRepository();const agent=await repo.getEmployeeByEmail("agent@thelatincenter.org");const ticket=(await repo.listTickets())[0];await repo.updateTicket(ticket.ticketUid,{operationUid:"10000000-0000-0000-0000-000000000003",expectedVersion:ticket.version,status:"RESOLVED"},agent!);const completion=repo.legacyCompletions.get(ticket.ticketNumber);expect(completion?.solved).toBe("Yes");expect(completion?.staff).toBe("Daniel Ortiz");expect(completion?.completedAt).toBeTruthy();});
});
